omnitrix/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('myapp.urls')),
]

urls.py
from django.urls import path
from myapp import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('aec_main/',views.aec_main,name = 'aec-main'),
    path('',views.login_page,name = 'login-page'),
    path('login/', views.login_view, name="login"),
    path('latlong_json/', views.latlong_json, name='latlong_json'),
    path('aec_register/', views.aec_register, name='aec-register'),
    path('encode_password/', views.encode_password,name="encode-password"),
    path('reset_password/',views.reset_password,name="reset_password"),
    # path('loginprocess/',views.loginprocess,name="loginprocess"),
    path('aec_modal/',views.aec_modal,name="aec_modal"),
    path('aec_otp/<str:pk>',views.aec_otp,name="aec_otp"), 
    path('aec_sweetalarm/',views.aec_sweetalarm,name="aec_sweetalarm"),
    path('aec_erroralerm/',views.aec_erroralerm,name="aec_erroralerm"),
    path('resend_otp/<str:pk>',views.resend_otp,name="resend_otp"),
    path('aec_regerror/',views.aec_regerror,name="aec_regerror"),  
    path('logout_request/',views.logout_request,name="logout-request"),
    path('country_databases/',views.country_databases,name="country_databases"),
    path('get_states/',views.get_states,name="get-states"),
    path('get_districts/',views.get_districts,name="get-districts"),
    path('aec_masterscreen/',views.aec_masterscreen,name="aec_masterscreen"),
    path('state_databases/',views.state_databases,name="state_databases"),
    path('district_databases/',views.district_databases,name="district_databases"),
    # path('add_countrydata/',views.add_countrydata,name="add_countrydata"),
    # path('delete_countrydata/',views.delete_countrydata,name="delete_countrydata"),
    path('aec_masterdata/',views.aec_masterdata,name="aec_masterdata"),
    path('aec_localbodydata/',views.aec_localbodydata,name="aec_localbodydata"),
    path('aec_talukdata/',views.aec_talukdata,name="aec_talukdata"),
    path('aec_villagedata/',views.aec_villagedata,name="aec_villagedata"),
    path('add_field/',views.add_field,name="add_field"),
    path('add_statefield/',views.add_statefield,name="add_statefield"),
    path('add_districtfield/',views.add_districtfield,name="add_districtfield"),
    path('delete_item/<country_id>/', views.delete_item, name='delete_item'),
    path('delete_stateitem/<state_id>/',views.delete_stateitem,name="delete_stateitem"), 
    path('delete_districtitem/<district_id>/',views.delete_districtitem,name="delete_districtitem"),
    path('delete_masteritem/<master_id>/',views.delete_masteritem,name="delete_masteritem"),
    path('delete_localbodyitem/<localbody_id>/',views.delete_localbodyitem,name="delete_localbodyitem"),
    path('delete_talukitem/<taluk_id>/',views.delete_talukitem,name="delete_talukitem"),
    path('delete_villageitem/<village_id>/',views.delete_villageitem,name="delete_villageitem"),
    path('add_masterfield/',views.add_masterfield,name="add_masterfield"),
    path('add_localbodyfield/',views.add_localbodyfield,name="add_localbodyfield"),
    path('add_talukfields/',views.add_talukfields,name="add_talukfields"),
    path('add_villagefields/',views.add_villagefields,name="add_villagefields"),
    # path('aec_data/',views.aec_data,name="aec_data"),
    path('edit_country/<int:country_id>/', views.edit_country, name='edit_country'),
    path('edit_district/<int:district_id/',views.edit_district,name="edit_district"),
    path('edit_state/<int:state_id>/',views.edit_state,name="edit_state"),
    path('edit_village/<int:village_id>',views.edit_village,name="edit_village"),
    path('edit_district/<int:district_id>/',views.edit_district,name="edit_district"),
    path('edit_master/<int:masterplan_id>/',views.edit_master,name="edit_master"),
    path('edit_localbody/<int:localbody_id>/',views.edit_localbody,name="edit_localbody"),
    path('edit_village/<int:village_id>/',views.edit_village,name="edit_village"),
    path('edit_taluk/<int:taluk_id>/',views.edit_taluk,name="edit_taluk"),
    # path('show_districts/',views.show_districts,name="show_districts"),
    path('get_district/', views.get_district, name='get_district'), 
    path('get_masterplan/<int:district_id>/', views.get_masterplan, name='get_masterplan'),
    path('aec_villagesurverylist/',views.aec_villagesurverylist,name="aec_villagesurverylist"),
    path('aec_landusedata/',views.aec_landusedata,name="aec_landusedata"),
    path('add_landusedata/',views.add_landusedata,name="add_landusedata"),
    path('delete_landuse/<landuse_id>/',views.delete_landuse,name="delete_landuse"),
    path('edit_landusedata/<int:landuse_id>/',views.edit_landusedata,name="edit_landusedata"),
    path('delete_villagesurvery/<villagesurvery_id>/',views.delete_villagesurvery,name="delete_villagesurvery"),
    path('add_villagesurvery/',views.add_villagesurvery,name="add_villagesurvery"),
    path('edit_villagesurvery/<int:villagesurvey_id>/',views.edit_villagesurvery,name="edit_villagesurvery"),
    path('delete_villagesurvey/<villagesurvey_id>/',views.delete_villagesurvey,name="delete_villagesurvey"),
    path('aec_townlist/',views.aec_townlist,name="aec_townlist"),
    path('add_townlist/',views.add_townlist,name="add_townlist"),
    path('edit_townlist/<int:townlist_id>/',views.edit_townlist,name="edit_townlist"),
    path('delete_townlist/<townlist_id>/',views.delete_townlist,name="delete_townlist"),
]

    

models.py
from django.db import models
from django_countries.fields import CountryField
from django.utils import timezone
from datetime import datetime 
from django.utils import timezone
from django.contrib.auth.models import User


#Registration Model
class Registration(models.Model):
    username = models.CharField(max_length=200)
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=255) # In real-world use cases, always use hashed passwords!
    phonenumber = models.CharField(max_length=300)
    otp = models.IntegerField(default= 000000)
    otp_count = models.IntegerField(default=0)
    otp_time = models.DateTimeField(null=True, blank=True)
    registered_user = models.IntegerField(default= 0)
    def __str__(self):
        return self.username

#Country Model
class Country(models.Model):
    country_id = models.IntegerField(default=0000)
    country=models.CharField(max_length=200,null=True,unique=True)
    def __str__(self):
        return self.country
    
#State Model
class State(models.Model):
    country=models.ForeignKey(Country,on_delete=models.CASCADE, null=True)
    state_id = models.IntegerField(default=0000)
    state=models.CharField(max_length=200,null=True,unique=True)
  
    def __str__(self):
        return self.state

#District Model
class District(models.Model):
    district_id = models.IntegerField(default=0000)
    district=models.CharField(max_length=200,null=True,unique=True)
    state=models.ForeignKey(State,on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.district
    
#masterplan Model
class Masterplan(models.Model):
    masterplan_id=models.IntegerField(default=0000)
    masterplan_name = models.CharField(max_length=200,null=True,unique=True)
    district = models.ForeignKey(District,on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.masterplan_name
    
#Localbody Model
class Localbody(models.Model):
    localbody_id=models.IntegerField(default=0000)
    localbody_name = models.CharField(max_length=200,null = True,unique=True)
    localbody_type = models.CharField(max_length=200,null = True)
    district = models.ForeignKey(District,on_delete=models.CASCADE, null=True)
    masterplan = models.ForeignKey(Masterplan,on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.localbody_name
    
#Taluk Model
class Talukmaster(models.Model):
    taluk_id=models.IntegerField(default=0000)
    taluk_name = models.CharField(max_length=200,null = True,unique=True)
    district = models.ForeignKey(District,on_delete=models.CASCADE, null=True)
    masterplan = models.ForeignKey(Masterplan,on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.taluk_name
    

#Village Model
class Villagemaster(models.Model):
    village_id=models.IntegerField(default=0000)
    village_name = models.CharField(max_length=200,null = True,unique=True)
    taluk = models.ForeignKey(Talukmaster,on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.village_name
    
#landuse Model
class Landuse(models.Model):
    landuse_id = models.AutoField(primary_key=True)
    landuse_type = models.CharField(max_length=100,unique=True)
    polygon_colour = models.CharField(max_length =50)
    def __str__(self):
        return self.landuse_type
 


#villagesurverylist MOdel
class villagesurverylist(models.Model):
    village_name = models.ForeignKey(Villagemaster,on_delete=models.CASCADE, null=True)
    landuse_type = models.ForeignKey(Landuse,on_delete=models.CASCADE, null=True)
    villagesurvey_id = models.AutoField(primary_key=True)
    surveyno_from = models.CharField(max_length=100,null = False)
    surveyno_to = models.CharField(max_length=100, null=True, blank=True)
    # landuse_detail = models.CharField(max_length=200)
    def __str__(self):
        return self.surveyno_from


class TownList(models.Model):
    townlist_id = models.AutoField(primary_key=True)
    wardno = models.CharField(max_length=10)
    blockno = models.CharField(max_length=10)
    surveyno_from = models.CharField(max_length=50)
    surveyno_to = models.CharField(max_length=70)
    landuse_type = models.ForeignKey(Landuse,on_delete=models.CASCADE, null=True)
    localbody_name=models.ForeignKey(Localbody,on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.wardno
  

templates/myapp/aec_modal.html
{% load static %}
<!DOCTYPE html>

  <html
    lang="en"
    class="light-style layout-navbar-fixed layout-menu-fixed"
    dir="ltr"
    data-theme="theme-default"
    data-assets-path="{% static 'assets/' %}"
    data-template="vertical-menu-template-no-customizer"
  >
  <head>
    <meta charset="utf-8"/>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    
    <title>
      {% block title %}
   
      {% endblock %}
    </title>
   
    <meta name="description" content="" />

     <!-- Favicon -->
     <link rel="icon" type="image/x-icon" href="{% static 'assets/vendor/libs/aec-source/cosai.png' %}" />
    
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/leaflet/leaflet.css' %}" />
     <link
      href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    /> 
    <!-- Google Fonts -->
    <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'assets/vendor/fonts/boxicons.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/fonts/fontawesome.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/fonts/flag-icons.css' %}" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="{% static 'assets/vendor/css/rtl/core.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/css/rtl/theme-default.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/typeahead-js/typeahead.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/apex-charts/apex-charts.css' %}" />

    <!-- Vendors CSS fixed datatable -->
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/typeahead-js/typeahead.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/datatables-bs5/datatables.bootstrap5.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/datatables-responsive-bs5/responsive.bootstrap5.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/datatables-select-bs5/select.bootstrap5.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/datatables-checkboxes-jquery/datatables.checkboxes.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/datatables-fixedcolumns-bs5/fixedcolumns.bootstrap5.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/datatables-fixedheader-bs5/fixedheader.bootstrap5.css' %}" />

    <!-- Vendors CSS sweet alert -->
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/animate-css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/sweetalert2/sweetalert2.css' %}" />
     
    <!-- report generation junior -->
    <link rel="stylesheet" href="{% static 'assets/vendor/libs/aec-source/aec.css' %}" />
  
    

    {% block stylesheet  %} {% endblock %}
 
    <!-- Page CSS -->

    <!-- Helpers -->
    <script src="{% static 'assets/vendor/js/helpers.js' %}"></script>
    

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{% static 'assets/js/config.js' %}"></script>
    <script src = "{% static 'assets/vendor/libs/report-gen/jquery.js' %}"></script>
   
    <!-- html starter -->

  </head>

  <body>
    <!-- Layout wrapper -->
    <div class="container-xxl">
      <div class="authentication-wrapper authentication-basic container-p-y">
        <div class="authentication-inner py-4">
          <!-- Register -->
   
                </a>
              </div>
              <!-- /Logo -->
              <form id="formAuthentication" class="mb-3" action="{% url 'login' %}" method="POST">
                {% csrf_token %}
                <br>
                <br>
                <div class="swal2-container swal2-center swal2-backdrop-show" style="overflow-y: auto;"><div aria-labelledby="swal2-title" aria-describedby="swal2-html-container" class="swal2-popup swal2-modal swal2-icon-success swal2-show" tabindex="-1" role="dialog" aria-live="assertive" aria-modal="true" style="display: grid;"><button type="button" class="swal2-close" aria-label="Close this dialog" style="display: none;">×</button><ul class="swal2-progress-steps" style="display: none;"></ul><div class="swal2-icon swal2-success swal2-icon-show" style="display: flex;"><div class="swal2-success-circular-line-left" style="background-color: rgb(255, 255, 255);"></div>
                <span class="swal2-success-line-tip"></span> <span class="swal2-success-line-long"></span>
                <div class="swal2-success-ring"></div> <div class="swal2-success-fix" style="background-color: rgb(255, 255, 255);"></div>
                <div class="swal2-success-circular-line-right" style="background-color: rgb(255, 255, 255);"></div>
                 </div><img class="swal2-image" style="display: none;"><h2 class="swal2-title" id="swal2-title" style="display: block;">Good job!</h2><div class="swal2-html-container" id="swal2-html-container" style="display: block;">Thank you for filling our form. We will keep your information safe.!</div><input class="swal2-input" style="display: none;"><input type="file" class="swal2-file" style="display: none;"><div class="swal2-range" style="display: none;"><input type="range"><output></output></div><select class="swal2-select" style="display: none;"></select><div class="swal2-radio" style="display: none;"></div><label for="swal2-checkbox" class="swal2-checkbox" style="display: none;"><input type="checkbox"><span class="swal2-label"></span></label><textarea class="swal2-textarea" style="display: none;"></textarea><div class="swal2-validation-message" id="swal2-validation-message" style="display: none;"></div><div class="swal2-actions" style="display: flex;"><div class="swal2-loader"></div><button type="button" class="swal2-confirm btn btn-primary" aria-label="" style="display: inline-block;">OK</button><button type="button" class="swal2-deny" aria-label="" style="display: none;">No</button><button type="button" class="swal2-cancel" aria-label="" style="display: none;">Cancel</button></div><div class="swal2-footer" style="display: none;"></div><div class="swal2-timer-progress-bar-container"><div class="swal2-timer-progress-bar" style="display: none;"></div></div></div></div>
                </div>
    <!--/ Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="{% static 'assets/vendor/libs/jquery/jquery.js' %}"></script>
    <script src="{% static 'assets/vendor/libs/popper/popper.js' %}"></script>
    <script src="{% static 'assets/vendor/js/bootstrap.js' %}"></script>
    <script src="{% static 'assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js' %}"></script>

    <script src="{% static 'assets/vendor/libs/hammer/hammer.js' %}"></script>

    <script src="{% static 'assets/vendor/libs/i18n/i18n.js' %}"></script>
    <script src="{% static 'assets/vendor/libs/typeahead-js/typeahead.js' %}"></script>

    <script src="{% static 'assets/vendor/js/menu.js' %}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->
    <script src="{% static 'assets/vendor/libs/datatables-bs5/datatables-bootstrap5.js' %}"></script>

    <script src="{% static 'assets/vendor/libs/formvalidation/dist/js/FormValidation.min.js' %}"></script>
    <script src="{% static 'assets/vendor/libs/formvalidation/dist/js/plugins/Bootstrap5.min.js' %}"></script>
    <script src="{% static 'assets/vendor/libs/formvalidation/dist/js/plugins/AutoFocus.min.js' %}"></script>

    <!-- Main JS -->
    <script src="{% static 'assets/js/main.js' %}"></script>

    <!-- Page JS -->
    <script src="{% static 'assets/js/app-access-roles.js' %}"></script>
    <script src="{% static 'assets/js/modal-add-role.js' %}"></script>


    <script>
      const button = document.querySelector("ok");

      button.addEventListener("click", (event) => {
       button.textContent = `Click count: ${event.detail}`;
});
</script>
<script>
</script>



  </body>
  </html>
    

templates/myapp/aec_statedata.html
{%extends 'myapp/aec_base.html' %}
{% load static %}
{% block content %}
  <div class="layout-page">

    <div class="content-wrapper">

        <div class="container-xxl flex-grow-1 container-p-y">
            <div class="row">
                <div class="col-12">
                    <div class="card mb-4">
                        <div class="card">
                            <div class="card">
                                <div class="card-header border-bottom">
                                  <h5 class="card-title">STATE MASTER</h5>
                                  <div class="d-flex justify-content-between align-items-center row py-3 gap-3 gap-md-0">
                                    <div class="col-md-4 user_role"></div>
                                    <div class="col-md-4 user_plan"></div>
                                    <div class="col-md-4 user_status"></div>
                                  </div>
                                </div>
                            <div class="card-datatable text-nowrap">
                              <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap5 no-footer"><div class="row"><div class="col-sm-12 col-md-6"><div class="dataTables_length" id="DataTables_Table_0_length"><label>Show <select name="DataTables_Table_0_length" aria-controls="DataTables_Table_0" class="form-select"><option value="10">10</option><option value="25">25</option><option value="50">50</option><option value="100">100</option></select> entries</label></div></div><div class="col-sm-12 col-md-6 d-flex justify-content-center justify-content-md-end"><div id="DataTables_Table_0_filter" class="dataTables_filter">

                                <button class="btn btn-label-primary" tabindex="0" aria-controls="DataTables_Table_0" type="button" data-bs-toggle="modal" data-bs-target="#addNewCCModal">
                                  <span><i class="bx bx-plus me-sm-1"></i> <span class="d-none d-sm-inline-block">Add New Record&nbsp;&nbsp;</span>
                                </span></button>&nbsp;&nbsp;
                            
                             
                            </div>
                           </div>
                        <div> 
                       
        <table>
            <div class="card-body">
                <div class="table-responsive text-nowrap">
                    <table class="table table-bordered">
                    <thead>
                        <tr>
                 
                        
                        <th>country name</th>
                        <th>state name</th>
                        <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody class="table-border-bottom-0" id="tableBody" style="max-height: 120px; overflow-y: auto;">
                        <tr >
                            {% for data in obj %}
                           
           
                       
                       <td value={{data.country_id}}>{{data.country}}</td>
                       <td value={{data.id}}>{{data.state}} </td>
                       <td>
                        <div class="dropdown">
                          <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bx bx-dots-vertical-rounded"></i>
                          </button>
                          <div class="dropdown-menu" style="">
                            <a class="dropdown-item"  onclick="editState('{{data.id}}', '{{data.state}}', '{{data.country.country}}')"><i class="bx bx-edit-alt me-1"></i> Edit</a>
                            <a class="dropdown-item" href="{% url 'delete_stateitem' data.id %}"><i class="bx bx-trash me-1"></i> Delete</a>
                          </div>
                        </div>
                      </td>
                        </tr>
                        {%endfor%}
                    </tbody>
                    </table>
                 <br>
                  <!-- Add state data -->
               
                <div class="modal fade" id="addNewCCModal" tabindex="-1" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered1 modal-simple modal-add-new-cc">
                    <div class="modal-content p-3 p-md-5">
                      <div class="modal-body">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        <div class="text-center mb-4">
                          <h3>Add State</h3>
                        </div>
                        
                        <form id="addnewcomponent" class="row g-3" onsubmit="return false">
                          {% csrf_token %}
                       
                            <div class="modal-body">
                              <div class="input-group">
                                <button class="btn btn-outline-primary" type="button">Select Country</button>
                       
                                <select type="text"  class="form-control" id="country" aria-label="Example select with button addon">
                                  <option selected="">Choose...</option>
         
                                  {% for data in countries %}
                                  <option value={{data.id}}>{{data.country}}</option>
                                  {% endfor %}
                                  </select>
                              </div>
                              <br>
                          
                              <div class="form-group">
                                
                                <label for="state_name">State Name</label>
                                <input type="text" id="state" name="state" class="form-control" required>
                              </div>
                              <div class="col-12 text-center mt-4">
                                <button type="submit" class="btn btn-primary me-sm-3 me-1">Save</button>
                                <button
                                  type="reset"
                                  class="btn btn-label-secondary btn-reset"
                                  data-bs-dismiss="modal"
                                  aria-label="Close">
                                  Cancel
                                </button>
                              </div>
                            </form>
                          </div>
                        </div>
                      </div>
                    </div>
                    <ul id="field-list">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
</div>


<!-- Update State List-->
<div class="modal fade" id="addNewCCModal1" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered1 modal-simple modal-add-new-cc">
    <div class="modal-content p-3 p-md-5">
      <div class="modal-body">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        <div class="text-center mb-4">
          <h3>Edit State</h3>
        </div>
        <form id="addnewcomponent1" class="row g-3" onsubmit="return true">
          {% csrf_token %}
          <div class="modal-body">
            <div class="form-group">
              <label for="state_name">Country Name</label>
              <input type="text" id="country-modal" name="country" class="form-control" required>
            </div>
           
            <div class="form-group">
              <label for="id_state_id"></label>
              <input type="hidden" id="id-modal" name="id" class="form-control" required>
            </div>
          <div class="form-group">         
            <label for="state_name">State Name</label>
            <input type="text" id="state-modal" name="state" class="form-control" required >
          </div>
          <div class="col-12 text-center mt-4">
            <button type="submit" class="btn btn-primary me-sm-3 me-1">Save Changes</button>
            <button type="reset" class="btn btn-label-secondary btn-reset" data-bs-dismiss="modal" aria-label="Close">
              Cancel
            </button>
          </div>
        {% if form.errors %}
            <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul>
        {% endif %}
     
      
        </form>
      </div>
    </div>
  </div>
</div>
                                                                   
 <script>
  function editState(id, state, country){
    $('#addNewCCModal1').modal("show");
    $("#country-modal").val(country);
    $("#state-modal").val(state);
    $("#id-modal").val(id);
    console.log(id, state, country)
  
    $('form#addnewcomponent1').submit(function (e) {
      e.preventDefault();
      console.log(" call8ng addnewcomponent")
      var empty = true;

      var state = $('#state-modal').val();
      console.log("state",state)
      var country = $('#country-modal').val();
      console.log("country",country)
      var state_id = $('#id-modal').val();
      console.log("state_id",state_id)
    $.ajax({
      url: '/edit_state/' + state_id + '/',  
      method: 'post',
      data: {
          state_id: state_id,
          state: state,
          country: country,
          csrfmiddlewaretoken: '{{ csrf_token }}'
      },
    dataType: 'json',
    success: function (data) {
        if (data.status) {
            sweet_alert_message('success', data.message);
        }  else {
          sweet_alert_message('success', data.message);
          setTimeout(function() {
            window.location.reload();
          }, 1000); 
        }
    }
  
  })
})
 
}



console.log('ajax')
  function sweet_alert_message(icons, message) {
  if (icons == "success") {
    title1 = "Good job!"
  } else if (icons == "info") {
    title1 == "Info!"
  } else if (icons == "warning") {
    title1 = "Warning!"
  } else {
    title1 = "Error!"
  }
  Swal.fire({
    title: title1,
    text: message,
    icon: icons,
    customClass: {
      confirmButton: 'btn btn-primary'
    },
    buttonsStyling: false
  });
  }

//######## component submission ######
  $('form#addnewcomponent').submit(function (e) {
  e.preventDefault();
  console.log(" call8ng addnewcomponent")
  var empty = true;
  var country = $('#country').val(); 
  //var id = $('#addnewcomponent.id').val();
  console.log(" country",country)
  console.log(" country",$('#country').val() )
  var state = $('#state').val();
  console.log("state",state)
  if (empty) {
  console.log('ajax callinnnnnnng')
    $.ajax({
    url: '/add_statefield/' ,
    method: 'post',
    data: {
    'country':country,
    'state':state,

    'csrfmiddlewaretoken': '{{ csrf_token }}'
    },
    dataType: 'json',

    success: function (data) {
    if (data.status) {

    sweet_alert_message('success', data.message)
    
    
  }  else {
    sweet_alert_message('success', data.message);
    setTimeout(function() {
      window.location.reload();
    }, 1000); 
  }
  }
  });

}
  console.log('ajax')

  });
  </script>
 
 

  {% endblock %}
